module.exports = [
  {
    _id: 'b5ec574a-5af4-4edc-979b-68b5c8d5ff3e',
    parent: null,
    name: 'Root',
    slug: 'root',
    rightsAvailable:['fullAccess', 'fullDeny'],
    isPrimary: true,
    status: true,
    deleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "0698943a-1bf5-4c73-b59b-fd614d718167",
    parent: null,
    name: "User Management",
    slug: "user-management",
    description: null,
    rightsAvailable: [],
    status: true,
    deleted: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
      _id: "bfc21cdc-1494-45eb-bfb7-c72bbc09f953",
      parent: "0698943a-1bf5-4c73-b59b-fd614d718167",
      name: "User Section",
      slug: "user-section",
      description: null,
      rightsAvailable: [
        "fullAccess",
        "fullDeny",
        "createNew",
        "deleteExisting",
        "downloadList",
        "downloadSingleDetails",
        "drop-downList",
        "listView",
        "manageColumns",
        "others",
        "singleDetailsView",
        "updateExisting"
      ],
      status: true,
      deleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
  },
  {
      _id: "5cdbee94-b6fa-40be-b351-8e2e5c7ae8b1",
      parent: "0698943a-1bf5-4c73-b59b-fd614d718167",
      name: "Role Section",
      slug: "role-section",
      description: null,
      rightsAvailable: [
        "fullAccess",
        "fullDeny",
        "createNew",
        "deleteExisting",
        "downloadList",
        "downloadSingleDetails",
        "drop-downList",
        "listView",
        "others",
        "singleDetailsView",
        "updateExisting"
      ],
      status: true,
      deleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
  },
  {
      _id: "3a79850b-e660-406a-9cea-1096fc63f10b",
      parent: "0698943a-1bf5-4c73-b59b-fd614d718167",
      name: "Resource Section",
      slug: "resource-section",
      description: null,
      rightsAvailable: [
        "fullAccess",
        "fullDeny",
        "createNew",
        "deleteExisting",
        "downloadList",
        "downloadSingleDetails",
        "drop-downList",
        "listView",
        "others",
        "singleDetailsView",
        "updateExisting"
      ],
      status: true,
      deleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
  },
  {
      _id: "08a59d4f-4434-4c94-bb65-62bb77df1ee2",
      parent: "0698943a-1bf5-4c73-b59b-fd614d718167",
      name: "Permission Section",
      slug: "permission-section",
      description: null,
      rightsAvailable: [
        "fullAccess",
        "fullDeny",
        "createNew",
        "deleteExisting",
        "drop-downList",
        "listView",
        "others",
        "singleDetailsView",
        "updateExisting"
      ],
      status: true,
      deleted: false,
      createdAt: new Date(),
      updatedAt: new Date(),
  }
];