module.exports = [
  {
    _id: '55bd6485-c7c6-44d3-af28-41cf1e405f4d',
    name: 'Full Access',
    slug: 'fullAccess',
    deleted: false,
    isPrimary: true,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '1d289bda-0754-4216-9ec6-9744cec4ffd8',
    name: 'List View',
    slug: 'listView',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'ef784f24-81f7-42a5-b725-cb4276cb06ac',
    name: 'Drop-down List',
    slug: 'drop-downList',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'bbfcaa93-2204-457c-861f-f6449d54c198',
    name: 'Single Details View',
    slug: 'singleDetailsView',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '99922a7d-4de4-41b3-979d-8ed90bb945e3',
    name: 'Create New',
    slug: 'createNew',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '352aff36-490d-4460-be48-841072e88657',
    name: 'Update Existing',
    slug: 'updateExisting',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '470a1743-7ed5-49ad-b136-8ac5ec9faeee',
    name: 'Delete Existing',
    slug: 'deleteExisting',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '841545f6-acb0-454b-a6f4-5b7474d04373',
    name: 'Download Single Details',
    slug: 'downloadSingleDetails',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '3f106fe3-861f-4bc7-9cd1-0ca42c312f2f',
    name: 'Download List',
    slug: 'downloadList',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '9ee3e047-65b1-4d08-9430-68d79ff992f8',
    name: 'Manage Columns',
    slug: 'manageColumns',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'beb193f8-4913-42ff-a515-136346e5db44',
    name: 'Others',
    slug: 'others',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: '58c95062-fa56-4c4c-8e3c-cb7450f389e5',
    name: 'Full Deny',
    slug: 'fullDeny',
    isPrimary: true,
    deleted: false,
    status: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  }
];